version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"  # ここを8080 → 8081などに変更
    volumes:
      - .:/var/www/html
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
